name: code_excerpt_updater
publish_to: none

environment:
  sdk: '>=2.11.99 <3.0.0'

dependencies:
  args: ^2.1.0
  logging: ^1.0.1
  path: ^1.4.0
  yaml: ^3.1.0

dev_dependencies:
  mockito: ^5.0.7
  test: ^1.14.1
