name: code_excerpter
publish_to: none

environment:
  sdk: '>=2.11.99 <3.0.0'

dependencies:
  build: ^2.0.1
  logging: ^1.0.1
  path: ^1.6.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.2
  test: ^1.0.0
