# Created with package:mono_repo v3.4.7
name: Dart CI
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2
      - name: mono_repo self validate
        run: pub global activate mono_repo 3.4.7
      - name: mono_repo self validate
        run: pub global run mono_repo generate --validate
  job_002:
    name: "analyzer_and_format; Dart 2.12.0; PKGS: packages/code_excerpt_updater, packages/code_excerpter; `dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:packages/code_excerpt_updater-packages/code_excerpter;commands:dartfmt-dartanalyzer"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:packages/code_excerpt_updater-packages/code_excerpter
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: "2.12.0"
      - id: checkout
        uses: actions/checkout@v2
      - id: packages_code_excerpt_updater_pub_upgrade
        name: "packages/code_excerpt_updater; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/code_excerpt_updater
        run: pub upgrade --no-precompile
      - name: "packages/code_excerpt_updater; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.packages_code_excerpt_updater_pub_upgrade.conclusion == 'success'"
        working-directory: packages/code_excerpt_updater
        run: dartfmt -n --set-exit-if-changed .
      - name: "packages/code_excerpt_updater; dartanalyzer --fatal-infos ."
        if: "always() && steps.packages_code_excerpt_updater_pub_upgrade.conclusion == 'success'"
        working-directory: packages/code_excerpt_updater
        run: dartanalyzer --fatal-infos .
      - id: packages_code_excerpter_pub_upgrade
        name: "packages/code_excerpter; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/code_excerpter
        run: pub upgrade --no-precompile
      - name: "packages/code_excerpter; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.packages_code_excerpter_pub_upgrade.conclusion == 'success'"
        working-directory: packages/code_excerpter
        run: dartfmt -n --set-exit-if-changed .
      - name: "packages/code_excerpter; dartanalyzer --fatal-infos ."
        if: "always() && steps.packages_code_excerpter_pub_upgrade.conclusion == 'success'"
        working-directory: packages/code_excerpter
        run: dartanalyzer --fatal-infos .
  job_003:
    name: "analyzer_and_format; Dart dev; PKGS: packages/code_excerpt_updater, packages/code_excerpter; `dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:packages/code_excerpt_updater-packages/code_excerpter;commands:dartfmt-dartanalyzer"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:packages/code_excerpt_updater-packages/code_excerpter
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2
      - id: packages_code_excerpt_updater_pub_upgrade
        name: "packages/code_excerpt_updater; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/code_excerpt_updater
        run: pub upgrade --no-precompile
      - name: "packages/code_excerpt_updater; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.packages_code_excerpt_updater_pub_upgrade.conclusion == 'success'"
        working-directory: packages/code_excerpt_updater
        run: dartfmt -n --set-exit-if-changed .
      - name: "packages/code_excerpt_updater; dartanalyzer --fatal-infos ."
        if: "always() && steps.packages_code_excerpt_updater_pub_upgrade.conclusion == 'success'"
        working-directory: packages/code_excerpt_updater
        run: dartanalyzer --fatal-infos .
      - id: packages_code_excerpter_pub_upgrade
        name: "packages/code_excerpter; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/code_excerpter
        run: pub upgrade --no-precompile
      - name: "packages/code_excerpter; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.packages_code_excerpter_pub_upgrade.conclusion == 'success'"
        working-directory: packages/code_excerpter
        run: dartfmt -n --set-exit-if-changed .
      - name: "packages/code_excerpter; dartanalyzer --fatal-infos ."
        if: "always() && steps.packages_code_excerpter_pub_upgrade.conclusion == 'success'"
        working-directory: packages/code_excerpter
        run: dartanalyzer --fatal-infos .
  job_004:
    name: "unit_test; Dart 2.12.0; PKGS: packages/code_excerpt_updater, packages/code_excerpter; `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:packages/code_excerpt_updater-packages/code_excerpter;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0;packages:packages/code_excerpt_updater-packages/code_excerpter
            os:ubuntu-latest;pub-cache-hosted;dart:2.12.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: "2.12.0"
      - id: checkout
        uses: actions/checkout@v2
      - id: packages_code_excerpt_updater_pub_upgrade
        name: "packages/code_excerpt_updater; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/code_excerpt_updater
        run: pub upgrade --no-precompile
      - name: packages/code_excerpt_updater; pub run test
        if: "always() && steps.packages_code_excerpt_updater_pub_upgrade.conclusion == 'success'"
        working-directory: packages/code_excerpt_updater
        run: pub run test
      - id: packages_code_excerpter_pub_upgrade
        name: "packages/code_excerpter; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/code_excerpter
        run: pub upgrade --no-precompile
      - name: packages/code_excerpter; pub run test
        if: "always() && steps.packages_code_excerpter_pub_upgrade.conclusion == 'success'"
        working-directory: packages/code_excerpter
        run: pub run test
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: "unit_test; Dart dev; PKGS: packages/code_excerpt_updater, packages/code_excerpter; `pub run test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:packages/code_excerpt_updater-packages/code_excerpter;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:packages/code_excerpt_updater-packages/code_excerpter
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2
      - id: packages_code_excerpt_updater_pub_upgrade
        name: "packages/code_excerpt_updater; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/code_excerpt_updater
        run: pub upgrade --no-precompile
      - name: packages/code_excerpt_updater; pub run test
        if: "always() && steps.packages_code_excerpt_updater_pub_upgrade.conclusion == 'success'"
        working-directory: packages/code_excerpt_updater
        run: pub run test
      - id: packages_code_excerpter_pub_upgrade
        name: "packages/code_excerpter; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/code_excerpter
        run: pub upgrade --no-precompile
      - name: packages/code_excerpter; pub run test
        if: "always() && steps.packages_code_excerpter_pub_upgrade.conclusion == 'success'"
        working-directory: packages/code_excerpter
        run: pub run test
    needs:
      - job_001
      - job_002
      - job_003
